### ISSUE TITLE
Use yaml file for coefficients in ISCCP-NG reader

### ISSUE THREAD

**Issue by ninahakansson** [foua-pps/level1c4pps#113]
We should move coefficients to yaml files in the ISCCP-NG reader. Suggestion from Bengt:

```
coeffcients:
  channels: 
    - refl_00_65um 
    - refl_00_86um
    - refl_01_60um  
    - temp_03_80um
    - temp_06_20um
    - temp_07_30um
    - temp_08_60um  
    - temp_09_70um
    - temp_11_00um
    - temp_12_00um
    - temp_13_30um'
  satellite: 
    GOES-16: 
      day:
        slope: [1.00152, 0.946758, 1.00669, 0.926764, 0.991329, 0.999300, 1.01977, 1.03453, 0.996781, 1.02343, 0.863748]
        offset: [0.000369844, 0.193868, 0.708022, 18.4795, 1.58729, -0.0312020, -4.93224, -7.83331, 1.13395, -5.51940, 30.5574]
      night: 
        ...
```
